# Generated by Django 2.1.5 on 2020-07-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_name', models.CharField(max_length=64)),
                ('temperature', models.FloatField()),
                ('ph_level', models.FloatField()),
                ('water_level', models.BooleanField()),
            ],
        ),
    ]
