# Generated by Django 2.1.5 on 2020-07-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pond', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='ph_level',
        ),
        migrations.RemoveField(
            model_name='pond',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='pond',
            name='water_level',
        ),
        migrations.AddField(
            model_name='pond',
            name='channel_id',
            field=models.IntegerField(default='0000000'),
        ),
    ]
