# Generated by Django 2.1.5 on 2020-07-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pond', '0003_pond_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='owner',
        ),
    ]
